#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common
# If troubleshooting:
if [[ -n "$DEBUG_LOGGING" ]]; then
    set -x
fi

# ensure this also works with dump978:
READSB_DEVICE_TYPE="${DUMP978_DEVICE_TYPE:-${READSB_DEVICE_TYPE}}"
READSB_ENABLE_BIASTEE="${DUMP978_ENABLE_BIASTEE:-${READSB_ENABLE_BIASTEE}}"
READSB_RTLSDR_DEVICE="${DUMP978_RTLSDR_DEVICE:-${READSB_RTLSDR_DEVICE}}"

if [[ "$READSB_DEVICE_TYPE" == "rtlsdr" ]]; then
    s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Device type is rtlsdr, checking for bias tee..."
    if chk_enabled "$READSB_ENABLE_BIASTEE"; then
        s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Trying to disable bias tee..."
        # Prepare temp file
        biast_tempfile=$(mktemp)
        # Attempt to get devices, use random serial so it's very unlikely we claim an SDR used by someone else
        rtl_biast -d "$RANDOM$RANDOM" > "$biast_tempfile" 2>&1 || true
        # Get number of devices
        num_devices=$(sed -n 's/^Found\s\+\([0-9]\+\)\s\+device(s):\s*$/\1/p' "$biast_tempfile")
        # If we have more than one device, we need a serial number
        if [[ "$num_devices" -gt 1 ]]; then
            s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Found $num_devices devices, checking for serial number..."
            if [[ -n "$READSB_RTLSDR_DEVICE" ]]; then
                # For each line...
                while read -r line; do
                    echo "$line"
                    # get device id for specific serial
                    # first try v3 sdrs
                    if echo "$line" | grep -oP '^([0-9]+):\s+(\w+),\s+(\w+),\s+SN:\s+([0-9az-A-Z]{1,8})\s*$' > /dev/null 2>&1; then
                        device_id=$(echo "$line" | sed -n 's/^\([0-9]\+\):\s\+\(\w\+\),\s\+\(\w\+\),\s\+SN:\s\+\([0-9a-zA-Z]\{1,8\}\)\s*$/\1/p')
                        device_manufacturer=$(echo "$line" | sed -n 's/^\([0-9]\+\):\s\+\(\w\+\),\s\+\(\w\+\),\s\+SN:\s\+\([0-9a-zA-Z]\{1,8\}\)\s*$/\2/p')
                        device_model=$(echo "$line" | sed -n 's/^\([0-9]\+\):\s\+\(\w\+\),\s\+\(\w\+\),\s\+SN:\s\+\([0-9a-zA-Z]\{1,8\}\)\s*$/\3/p')
                        device_serial=$(echo "$line" | sed -n 's/^\([0-9]\+\):\s\+\(\w\+\),\s\+\(\w\+\),\s\+SN:\s\+\([0-9a-zA-Z]\{1,8\}\)\s*$/\4/p')

                        if [[ "$device_serial" == "$READSB_RTLSDR_DEVICE" ]] && chk_enabled "$READSB_ENABLE_BIASTEE"; then
                            s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Disabling bias tee for device $device_id:  $device_manufacturer, $device_model, SN: $device_serial"
                            # shellcheck disable=SC2016
                            s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args rtl_biast -d "$device_id" -b 1
                        fi
                        # if not, lets try for v4
                    elif echo "$line" | grep -oP '^([0-9]+):\s+(\w+,?\s?\w+\s?\w+),\s+SN:\s+([0-9]{1,8})\s*$' > /dev/null 2>&1; then
                        device_id=$(echo "$line" | sed -n 's/\([0-9]\+\):\s\+\(\w\+\),\s\+\(\w\+\s\+\w\+\),\s\+SN:\s\+\([0-9a-zA-Z]\{1,8\}\)\s*$/\1/p')
                        device_manufacturer=$(echo "$line" | sed -n 's/\([0-9]\+\):\s\+\(\w\+\),\s\+\(\w\+\s\+\w\+\),\s\+SN:\s\+\([0-9a-zA-Z]\{1,8\}\)\s*$/\2/p')
                        device_model=$(echo "$line" | sed -n 's/\([0-9]\+\):\s\+\(\w\+\),\s\+\(\w\+\s\+\w\+\),\s\+SN:\s\+\([0-9a-zA-Z]\{1,8\}\)\s*$/\3/p')
                        device_serial=$(echo "$line" | sed -n 's/\([0-9]\+\):\s\+\(\w\+\),\s\+\(\w\+\s\+\w\+\),\s\+SN:\s\+\([0-9a-zA-Z]\{1,8\}\)\s*$/\4/p')

                        if [[ "$device_serial" == "$READSB_RTLSDR_DEVICE" ]] && chk_enabled "$READSB_ENABLE_BIASTEE"; then
                            s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Disabling bias tee for device $device_id:  $device_manufacturer, $device_model, SN: $device_serial"
                            # shellcheck disable=SC2016
                            s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args rtl_biast -d "$device_id" -b 0
                        fi
                    fi
                done < "$biast_tempfile"
            fi
        else
            s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Disabling bias tee..."
            # shellcheck disable=SC2016
            s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args rtl_biast -b 0
        fi
        rm "$biast_tempfile"
    else
        s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "READSB_ENABLE_BIASTEE not enabled, skipping..."
    fi
else
    s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Device type is not rtlsdr, skipping..."
fi
